title: W3C/OGC Joint Workshop Series on Maps for the Web
description: >-
  Distributed, online workshops to discuss
  best practices and potential standardization
  of map viewers built using the web platform
url: "https://maps4html.org/Maps4HTML-Workshop-2020"

theme: null

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
