title: W3C/OGC Joint Workshop Series on Maps for the Web
description: >-
  Distributed, online workshops to discuss
  best practices and potential standardization
  of map viewers built using the web platform
url: "https://www.w3.org/2020/maps"

theme: null

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
